################################################
# Dexcom's SwiftLint Common Configuration File #
# SwiftLint Version 0.47.0                     #
################################################

# Files/Directories to exclude from swiftlint

excluded:
  - Pods
  - fastlane
  - vendor
  - ThirdParty
  # Note: Include app specific folders that should be excluded.

# Rule identifiers to exclude from running

disabled_rules:
  - trailing_whitespace
  - function_parameter_count
  - nesting

# Rule identifiers to opt-in when running

opt_in_rules:
  - anyobject_protocol
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - identical_operands
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition

######################
# Configurable rules #
######################

# Note: Modify the following rules according to your team needs.

cyclomatic_complexity:
  warning: 15
  ignores_case_statements: true

file_length:
  warning: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 200

identifier_name:
  min_length:
    error: 2
  excluded:
    - G6
    - G7
    - id
    - i
    - x
    - y
    - z

large_tuple:
  warning: 4
  error: 5

line_length:
  warning: 200

type_body_length:
  warning: 500
  error: 800

type_name:
  max_length: 60

################
# Custom rules #
################

custom_rules:

  string_initialization:
    included: ".*\\.swift"
    name: String Initialization
    message: For strings, it is preferred to use string literals.
    regex: \bString\b\(".*"\)
    severity: warning

  empty_array_initialization:
    included: ".*\\.swift"
    name: Empty Array Initialization
    message: For empty arrays, it is preferred to use type inference.
    regex: (let|var)\s+[\w\d]+:\s?\[[\w\d]+\]\s?=\s?\[\]
    severity: warning

  empty_dictionary_initialization:
    included: ".*\\.swift"
    name: Empty Dictionary Initialization
    message: For dictionaries arrays, it is preferred to use type inference.
    regex: (let|var)\s+[\w\d]+:\s?\[[\w\d]+\s?:\s+[\w\d]+\]\s?=\s?\[:\]
    severity: warning

  empty_localized_string_comment:
    included: ".*\\.swift"
    name: Empty Localized String Comment
    message: For localized strings, it is preferred to have a comment.
    regex: NSLocalizedString\(\"[^"]*\",(\s+tableName:\s+\"[^"]*\",)?\s+comment:\s+(nil|"")\)
    severity: warning

  unnecessary_else_statement:
    included: ".*\\.swift"
    name: Unnecessary Else Statement
    message: In conditional statements, it is preferred to avoid an else statement when the previous condition finishes execution.
    regex: \}\s+else\s+\{\s+return
    severity: warning

  unnecessary_property_type:
    included: ".*\\.swift"
    name: Unnecessary Property Type
    message: When declaring a property with a default value, the property type should be avoided.
    regex: (let|var)\s[\w\d]+\s?:\s?(Int|String|Double|Bool|Data)+\s?=\s?[\w\d]+
    severity: warning

  comment_spacing:
    included: ".*\\.swift"
    name: Comment Spacing
    message: When writting a comment, it is preferred to add a whitespace after the comment.
    regex: ^[ \t]+\/\/\w
    severity: warning
